export const pagePaths = {
    root: "/",
    signIn: "/sign-in",
    createAccount: "/create-account",
    cartPage: "/cart-page",
    myOrderPage: "/my-order-page",
    shippingPage: "/shipping-page",
    ShippingPageFromPDP: "/shipping-page-pdp",
    paymentPages: "/payment-pages",
    dummyTest: "/dummy-test",
    careerPage: "/career-page",
    contactUsPage: "/contact-us",
    products:"/products/:id",
    aboutUsPage:"/about-us",
    cancellationPage:"/cancelletion",
    cancellationPolicy:"cancellations-policy",
    faq:"/faq",
    pressRealese:"/press-release",
    privacyPolicy:"/privacy-policy",
    productDetailsPage:"/product-details",
    shippingPolicy:"/shipping-policy",
    sitemap:"/site-map",
    termsOfServices:"/terms-of-services",
    wishlistPage:"/wishlist",
    shippingConfirmPage:"/shippingConfirm/:orderID",
}